# Generated by Django 4.0.6 on 2022-07-29 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import transactions.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('COM', 'Complete'), ('FAI', 'Failed'), ('CAN', 'Cancelled'), ('REF', 'Refunded')], max_length=4)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_id', to=settings.AUTH_USER_MODEL, validators=[transactions.models.is_vendor])),
            ],
        ),
    ]
