# Generated by Django 4.0.6 on 2022-07-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('COM', 'Complete'), ('FAI', 'Failed'), ('CAN', 'Cancelled'), ('REF', 'Refunded'), ('UNK', 'Unknown')], max_length=4),
        ),
    ]
